import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc   = os.path.join('SoftwareRelease','Imaging.jl','2DLSRTM')
files = ['marmousi_2D.segy','marmousi_migration_velocity.h5'];

# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
