#!/bin/bash
# https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.1-linux-x86_64.tar.gz
jver=0.6
jtar=julia-0.6.2-linux-x86_64.tar.gz
dver=julia-d386e40c17
jurl=https://julialang-s3.julialang.org/bin/linux/x64/$jver/$jtar

which curl 1>/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo FATAL ERROR: no curl executable found. Download and install Julia manually.
    exit 1
fi

#set -x
test -d $SLIM_JLAPPS/downloads || mkdir $SLIM_JLAPPS/downloads
cd $SLIM_JLAPPS/downloads || exit 1

rm -rf julia-*
curl $jurl | tar -xz
if [ $? -ne 0 ]; then
    echo FATAL ERROR: transfer failed. Try again.
    exit 1
fi
if [ ! -d $dver ]; then
    echo FATAL ERROR: name of the directory in th tarball has changed.
    echo ... Download and install Julia manually.
    exit 1
fi

test -d $SLIM_JLAPPS/Julia && rm -rf $SLIM_JLAPPS/Julia
mv $dver $SLIM_JLAPPS/Julia
echo JULIAHOME=$SLIM_JLAPPS/Julia
julia --version
