#!/usr/bin/env python
import sys

pv='.'.join([str(sys.version_info.major), str(sys.version_info.minor), str(sys.version_info.micro)])
if sys.version_info < (2,5,9):
    print "FATAL ERROR: Python version is too old", "("+pv+")"
else:
    print "Python version is sufficient", "("+pv+")"
